# /usr/local/bin/docker-compose -f /docs/dev-ops/environment/environment-docker-compose.yml up -d
version: '3.8'
# docker-compose -f environment-docker-compose.yml up -d
services:
  chatgpt-data-app:
    image: wang/chatgpt-data-app:1.1
    container_name: chatgpt-data-app
    ports:
      - "8091:8091"
    environment:
      - TZ=PRC
      - SERVER_PORT=8091
      - APP_CONFIG_API_VERSION=v1
      - APP_CONFIG_CROSS_ORIGIN=*
      - THREAD_POOL_EXECUTOR_CONFIG_CORE_POOL_SIZE=20
      - THREAD_POOL_EXECUTOR_CONFIG_MAX_POOL_SIZE=50
      - THREAD_POOL_EXECUTOR_CONFIG_KEEP_ALIVE_TIME=5000
      - THREAD_POOL_EXECUTOR_CONFIG_BLOCK_QUEUE_SIZE=5000
      - THREAD_POOL_EXECUTOR_CONFIG_POLICY=CallerRunsPolicy
      - CHATGPT_SDK_CONFIG_API_HOST=https://open.bigmodel.cn/
      - CHATGPT_SDK_CONFIG_API_KEY=395f31326c14d475cb273747f76a80a0.wo6jyLZMFSGnkdqP
      - WX_CONFIG_ORIGINALID=gh_be110517359f
      - WX_CONFIG_APPID=wx9c025268c749dea3
      - WX_CONFIG_TOKEN=b8b6
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always

  chatgpt-web:
    container_name: chatgpt-web
    image: wang/chatgpt-web:1.0
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_HOST_URL=http://localhost:8091
    restart: always
